USE KhelAkhe_CRM;


INSERT  INTO [dbo].[drs_error_message_mst] ([MessageCode], [MessageText], [MessageType], [HttpStatusCode], [IsActive], [IsDeleted], [CreatedDate])
VALUES                                    ('LOGIN_SUCCESS', 'Login successful.', 'SUCCESS', 200, 1, 0, GETDATE()),
('LOGOUT_SUCCESS', 'Logout successful.', 'SUCCESS', 200, 1, 0, GETDATE()),
('TOKEN_REFRESHED', 'Token refreshed successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('PASSWORD_CHANGED', 'Password changed successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('PASSWORD_RESET_REQUESTED', 'Password reset request generated successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('CUSTOMER_CREATED', 'Customer created successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('CUSTOMER_UPDATED', 'Customer updated successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('CUSTOMER_DELETED', 'Customer deleted successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('ADDRESS_CREATED', 'Address created successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('ADDRESS_UPDATED', 'Address updated successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('CATEGORY_CREATED', 'Category created successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('CATEGORY_UPDATED', 'Category updated successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('PRODUCT_CREATED', 'Product created successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('PRODUCT_UPDATED', 'Product updated successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('PRODUCT_DELETED', 'Product deleted successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('STOCK_ADDED', 'Stock added successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('STOCK_UPDATED', 'Stock updated successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('SUCCESS', 'Operation completed successfully.', 'SUCCESS', 200, 1, 0, GETDATE()),
('INVALID_REQUEST', 'Invalid request parameters.', 'ERROR', 400, 1, 0, GETDATE()),
('REQUEST_BODY_REQUIRED', 'Request body is required.', 'ERROR', 400, 1, 0, GETDATE()),
('VALIDATION_FAILED', 'Validation failed for the request.', 'ERROR', 400, 1, 0, GETDATE()),
('INVALID_CREDENTIALS', 'Invalid email/mobile or password.', 'ERROR', 401, 1, 0, GETDATE()),
('UNAUTHORIZED', 'Authentication is required to access this resource.', 'ERROR', 401, 1, 0, GETDATE()),
('INVALID_TOKEN', 'Invalid or expired access token.', 'ERROR', 401, 1, 0, GETDATE()),
('INVALID_REFRESH_TOKEN', 'Invalid or expired refresh token.', 'ERROR', 401, 1, 0, GETDATE()),
('REFRESH_TOKEN_REQUIRED', 'Refresh token is required.', 'ERROR', 401, 1, 0, GETDATE()),
('FORBIDDEN', 'You do not have permission to access this resource.', 'ERROR', 403, 1, 0, GETDATE()),
('ACCOUNT_DISABLED', 'Account is disabled.', 'ERROR', 403, 1, 0, GETDATE()),
('ACCOUNT_SUSPENDED', 'Account is suspended.', 'ERROR', 403, 1, 0, GETDATE()),
('ACCOUNT_TERMINATED', 'Account is terminated.', 'ERROR', 403, 1, 0, GETDATE()),
('ACCOUNT_TEMPORARILY_LOCKED', 'Account is temporarily locked due to multiple failed login attempts.', 'ERROR', 423, 1, 0, GETDATE()),
('CUSTOMER_NOT_FOUND', 'Customer record not found.', 'ERROR', 404, 1, 0, GETDATE()),
('CUSTOMER_ALREADY_EXISTS', 'Customer with given email or mobile already exists.', 'ERROR', 409, 1, 0, GETDATE()),
('ADDRESS_NOT_FOUND', 'Customer address record not found.', 'ERROR', 404, 1, 0, GETDATE()),
('CATEGORY_NOT_FOUND', 'Product category not found.', 'ERROR', 404, 1, 0, GETDATE()),
('CATEGORY_ALREADY_EXISTS', 'Product category with given name already exists.', 'ERROR', 409, 1, 0, GETDATE()),
('PRODUCT_NOT_FOUND', 'Product not found.', 'ERROR', 404, 1, 0, GETDATE()),
('PRODUCT_ALREADY_EXISTS', 'Product with given code or SKU already exists.', 'ERROR', 409, 1, 0, GETDATE()),
('INVALID_PRODUCT_ID', 'Invalid product ID specified.', 'ERROR', 400, 1, 0, GETDATE()),
('STOCK_NOT_FOUND', 'Stock information not found for product.', 'ERROR', 404, 1, 0, GETDATE()),
('RATE_LIMIT_EXCEEDED', 'Too many requests. Please try again later.', 'ERROR', 429, 1, 0, GETDATE()),
('SERVER_ERROR', 'An unexpected error occurred on the server.', 'ERROR', 500, 1, 0, GETDATE());
